template:
  - sensor:
      - name: "Sump Pump Water Level"
        unit_of_measurement: "mm"
        icon: mdi:water
        state: "{{ 500 - states('sensor.sump_pump_level') | int }}"
  - binary_sensor:
      - name: sump_pump_offline
        state: "{{ as_timestamp(states('sensor.date_time_iso')) - as_timestamp(states.sensor.sump_pump_level.last_updated) > 600 }}"

input_boolean:
  sump_pump_draining:
    name: sump_pump_draining
    icon: mdi:weather-tornado
