substitutions:
  name: sump-pump
packages:
  esphome.esp_web_tools_example: github://esphome/example-configs/esp-web-tools/esp32.yaml@v1
esphome:
  name_add_mac_suffix: false
  includes:
    - sump.h
sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new ProximitySensor(id(uart_bus));
    App.register_component(my_sensor);
    return {my_sensor};

  sensors:
    name: "Sump Pump Proximity Sensor"
    unit_of_measurement: mm
    id: sump_pump_proximity
    accuracy_decimals: 0

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .proximity
  #power_save_mode: none
  fast_connect: true
  manual_ip:
    static_ip: !secret sump_pump_ip
    gateway: !secret wifi_gateway
    dns1: !secret wifi_dns
    subnet: !secret wifi_subnet